object BuildDependenciesVersions {
    //app level
    const val GRADLE_ANDROID = "4.2.1"
    const val KOTLIN = "1.5.20"
    const val NAVIGATION = "2.3.2"
    const val DAGGER_HILT_GRADLE = "2.37"
    const val PROTOBUF_GRADLE = "0.8.13"
    const val GOOGLE_SERVICES = "4.3.4"
    const val FIREBASE_CRASHLYTICS_GRADLE = "2.4.1"
    const val JUNIT5_GRADLE = "1.7.0.0"

    //libs
    const val appCompatX = "1.3.1"
    const val coreKtxAndroidX = "1.6.0"
    const val constraintLayoutX = "2.0.4"
    const val coordinatorLayoutX = "1.1.0"
    const val multidex = "2.0.1"
    const val swipeRefreshLayout = "1.1.0"

    const val retrofit = "2.9.0"
    const val gson = "2.8.7"
    const val okHttp3 = "3.12.6"
    const val timber = "4.7.1"
    const val glide = "4.12.0"
    const val roomKtx = "2.3.0"
    const val gridLayout = "30.0.0"
    const val recyclerview = "30.0.0"
    const val easyPermissions = "3.0.0"

    const val androidxTestCore = "1.3.0"
    const val androidxTestCoreTesting = "2.1.0"
    const val junit4= "4.12"
    const val junitJupiter= "5.7.1"
    const val hamcrest = "1.3"
    const val kotlinxCoroutinesTest = "1.4.3"
    const val googleTruth = "1.1.2"
    const val mockitoCore = "3.8.0"
    const val mockitoInline = "3.8.0"
    const val mockitoKotlin = "2.2.0"
    const val junit5AndroidTest = "1.2.1"
    const val dexMakerMockito= "2.28.1"
    const val androidArchCoreTesting = "2.1.0"
    const val espresso = "3.3.0"
    const val espressoContribAndroidX = "3.3.0"
    const val espressoRulesAndroidX = "1.3.0"
    const val fragmentTestingAndroidX = "1.3.2"
    const val FRAGMENT_TEST = "1.3.2"
    const val RULES_TEST = "1.3.0"
    const val androidXJunitVersion = "1.1.2"
    const val RUNNER_TEST = "1.3.0"
    const val ROBOLECTRIC = "4.5.1"

    const val materialGoogleAndroid = "1.4.0"
    const val lifecycleAndroidX = "2.3.1"

    const val kotlinxCoroutines = "1.5.1"
    const val fragmentKtxAndroidX = "1.3.6"
    const val activityKtxAndroidX = "1.2.4"
    const val navigationKtxAndroidX = "2.3.5"
    const val preferenceKotlinAndroidX = "1.1.1"

    const val dagger = "2.37"
    const val hiltAndroidX = "1.0.0"
    const val daggerHiltAndroidTesting = "2.37"
    const val daggerHiltAndroid = "2.37"
    const val daggerHiltTesting = "2.37"

    const val cameraAndroidX = "1.0.0-rc01"
    const val cameraView = "1.0.0-alpha20"
    const val cameraExtensions = "1.0.0-alpha20"

    const val firebase = "26.2.0"
    const val mlkitBarcodeScanning = "16.0.3"
    const val biometric = "1.0.1"
    const val workRuntime = "2.5.0"

    const val leakCanary = "2.6"
    const val serviceLocation = "18.0.0"
    const val exifinterface = "1.3.3"
}